### ISSUE TITLE
Is there a description of the project?

### ISSUE THREAD

**Issue by ThorsenRune** [Junak/android_kernel_custom_a6plte#1]

**Comment by tmvkrpxl0** [comment]
It's custom kernel for Samsung Galaxy A6 plus

**Comment by ThorsenRune** [comment]
Sounds great. I'm quite annoyed about all the bloatware and undisable automatic updates on my A6 pls. I have tried rooting but messed it all up. Do you have any information of how to use this for rooting?

**Comment by tmvkrpxl0** [comment]
> 
> 
> Sounds great. I'm quite annoyed about all the bloatware and undisable automatic updates on my A6 pls. I have tried rooting but messed it all up. Do you have any information of how to use this for rooting?

Do you know how to build this? If so, you could just build it yourself and flash it

**Comment by ThorsenRune** [comment]
Thanks for you answer. 
No I have never build a kernel so I have to learn. Isn't there a readybuilt binary that I can just flash?
I tried some (two) from XDA but they didnt allow the phone to get past the ANDROID startup screen. Maybe its something to do with KNOX. Do you think this one can work?

**Comment by Junak** [comment]
> bloatware and undisable automatic updates

Only way this kernel can help you with those is by not booting stock ROM at all.

**Comment by ThorsenRune** [comment]
Sorry I don't understand. So this is a stock ROM? 
In other words is this the kernel I should try to solve the bloatware issues?

**Comment by Junak** [comment]
No, Stock ROM won't boot with this kernel.

**Comment by ThorsenRune** [comment]
Ehh, sorry but Im not so into the details. So I would need to find a ROM as well as build this kernel?

**Comment by tmvkrpxl0** [comment]
This kernel disables some security stuffs, because of that, Stock Rom won't boot
If you want to use this kernel, you must use custom rom
that means, you have to use roms like AOSP, Havoc, AEX or Lineage
if those rom doesn't have problem with booting on A6 plus, they'll boot
but if you want to use rooted stock rom, you must install magisk after installing twrp
